name: visitCardCICD

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: "weikelake/visitcard:v2"
  CONTAINER_NAME: "visitcard"
  

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build Docker image
        run: make build
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_ACCESS_TOKEN }}
      - name: push
        run: docker push $(echo $IMAGE_NAME)
  deploy:
    runs-on: ubuntu-latest
    needs: [build_and_push]
    steps:
      - name: sshlogin
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: IMAGE_NAME, CONTAINER_NAME
          script: | 
            # Stop running container
            docker stop $(echo $CONTAINER_NAME)
            
            # Remove old container
            docker rm $(echo $CONTAINER_NAME)
            
            # Remove old image
            docker rmi $(echo $IMAGE_NAME)
            
            # Get new image from Dockerhub
            docker pull $(echo $IMAGE_NAME)
            
            # Run a new container from a new image
            docker run -p 443:443 -p 80:8080 -v certs:/go/visitCard/certs -d \
            --restart always \
            --name $(echo $CONTAINER_NAME) $(echo $IMAGE_NAME)
  
  health:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: URL Health check
        uses: Jtalk/url-health-check-action@v2.2
        with:
          # Check the following URLs one by one sequentially
          url: https://${{ secrets.HOST }}/api/health
          # Follow redirects, or just report success on 3xx status codes
          follow-redirect: false # Optional, defaults to "false"
          # Fail this action after this many failed attempts
          max-attempts: 3 # Optional, defaults to 1
          # Delay between retries
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
          # Retry all errors, including 404. This option might trigger curl upgrade.
          retry-all: false # Optional, defaults to "false"

            
            
      


