name: visitCardCICD

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: "hub.docker.com"
  IMAGE_NAME: "weikelake/visitcard:v2"
  CONTAINER_NAME: "visitcard"
  

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Docker image
        run: make build
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_ACCESS_TOKEN }}
      - name: push
        run: docker push $(echo $IMAGE_NAME)
      


